//RUNS THE APPLICATION//
// import classes from other files
const Employee = require('./lib/Employee');
const Engineer = require('./lib/Engineer');
const Intern = require('./lib/Intern');
const Manager = require('./lib/Manager');

// require enquirer to get answers and fs to read and write file
const inquirer = require('inquirer');
const fs = require('fs');

// based on answers call on constructor to create a new manager, intern, engineer 


// if they say yes to any prompt get those values in your promise and pass in those values


// console log (Please enter team members info to generate team)
// prompt  will contain team members 
//starting with Team Manager's :name/ id / email / office number 
// then ask from options which type of team member would you like to add next?
// then prompt user with options: engineer, intern, I dont want to add any more members 
// if another type of member is chosen prompt questions 
// name? id? email? office number?
//when I dont want to add any more team members is chosen
//generates an html file with team members info on cards generated by html 



//1//create classes for each so those tests pass//*

//2//then index.js write code and use inquirer to  get answers 

//3// based on those answers call constructor to create new inter, manager, engineer 

//4//pass in those properties to get your manager, enginner, intern objects

//5// then call constructors and all their values




