// employee is a parent class 



// console log (Please enter team members info to generate team)
// prompt  will contain team members 
//starting with Team Manager's :name/ id / email / office number 
// then ask from options which type of team member would you like to add next?

// then prompt user with options: engineer, intern, I dont want to add any more members 

// if another type of member is chosen prompt questions 
// name? id? email? office number?

//when I dont want to add any more team members is chosen

//generates an html file with team members info on cards generated by html 




// create classes for each so those tests pass

//then index.js write code and use inquirer to  get answers 

// based on those answers call constructor to create new inter, manager, engineer 

//pass in those properties to get your manager, enginner, intern objects

// then call constructors and all their values





